### ISSUE TITLE
Please don't lead people to fake magisk websites

### ISSUE THREAD

**Issue by cizordj** [eurekadevelopment/eurekadevelopment.github.io#21]
Magisk is a critical software that runs on your phone and manages root access, in other words, many attackers try to take over this program by creating fake websites that claim to be 'official' when in fact they ship malicious versions of Magisk to hack into your phone. With that in mind I'm asking you guys, please don't lead people to those websites.

Words from [topjohnwu](https://github.com/topjohnwu) himself:

> [Github](https://github.com/topjohnwu/Magisk/) is the only source where you can get official Magisk information and downloads.

Please use the following page when teaching people where to download Magisk:
https://github.com/topjohnwu/Magisk/releases

Also note that `Magisk-v25.2.apk` is also a **flashable.zip**, so there is no need for two separate links.

Best regards.

**Comment by neikos4962** [comment]
@cizordj What?

**Comment by cizordj** [comment]
Thanks @kevios12 for solving this issue [#ec5c05f252551fc418dc62d7cfc6fc1bc06c850b](https://github.com/eurekadevelopment/eurekadevelopment.github.io/commit/ec5c05f252551fc418dc62d7cfc6fc1bc06c850b)
